using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DashboardAbast.Shared.Model.AxCasino
{
    [Table("PURCHLINE")]
    public partial class Purchline
    {
        [Key]
        [Column("PURCHID")]
        public string Purchid { get; set; } = null!;
        [Column("LINENUM", TypeName = "decimal(18,2)")]
        public decimal Linenum { get; set; }
        [Column("ITEMID")]
        public string Itemid { get; set; } = null!;
        [Column("PURCHSTATUS")]
        public int Purchstatus { get; set; }
        [Column("SHIPPINGDATEREQUESTED")]
        public DateTime Shippingdaterequested { get; set; }
        [Column("LEDGERACCOUNT")]
        public string Ledgeraccount { get; set; } = null!;
        [Column("DELIVERYDATE")]
        public DateTime Deliverydate { get; set; }
        [Column("NAME")]
        public string Name { get; set; } = null!;
        [Column("TAXGROUP")]
        public string Taxgroup { get; set; } = null!;
        [Column("QTYORDERED", TypeName = "decimal(18,2)")]
        public decimal Qtyordered { get; set; }
        [Column("PURCHRECEIVEDNOW", TypeName = "decimal(18,2)")]
        public decimal Purchreceivednow { get; set; }
        [Column("REMAINPURCHPHYSICAL", TypeName = "decimal(18,2)")]
        public decimal Remainpurchphysical { get; set; }
        [Column("REMAINPURCHFINANCIAL", TypeName = "decimal(18,2)")]
        public decimal Remainpurchfinancial { get; set; }
        [Column("PRICEUNIT", TypeName = "decimal(18,2)")]
        public decimal Priceunit { get; set; }
        [Column("PURCHPRICE", TypeName = "decimal(18,2)")]
        public decimal Purchprice { get; set; }
        [Column("CURRENCYCODE")]
        public string Currencycode { get; set; } = null!;
        [Column("LINEPERCENT", TypeName = "decimal(18,2)")]
        public decimal Linepercent { get; set; }
        [Column("LINEDISC", TypeName = "decimal(18,2)")]
        public decimal Linedisc { get; set; }
        [Column("LINEAMOUNT", TypeName = "decimal(18,2)")]
        public decimal Lineamount { get; set; }
        [Column("EXTERNALITEMID")]
        public string Externalitemid { get; set; } = null!;
        [Column("PURCHUNIT")]
        public string Purchunit { get; set; } = null!;
        [Column("DIMENSION")]
        public string Dimension { get; set; } = null!;
        [Column("DIMENSION2_")]
        public string Dimension2 { get; set; } = null!;
        [Column("DIMENSION3_")]
        public string Dimension3 { get; set; } = null!;
        [Column("DIMENSION4_")]
        public string Dimension4 { get; set; } = null!;
        [Column("CONFIRMEDDLV")]
        public DateTime Confirmeddlv { get; set; }
        [Column("ADDRESSREFRECID")]
        public long Addressrefrecid { get; set; }
        [Column("INVENTTRANSID")]
        public string Inventtransid { get; set; } = null!;
        [Column("VENDGROUP")]
        public string Vendgroup { get; set; } = null!;
        [Column("VENDACCOUNT")]
        public string Vendaccount { get; set; } = null!;
        [Column("ADDRESSREFTABLEID")]
        public int Addressreftableid { get; set; }
        [Column("PURCHQTY", TypeName = "decimal(18,2)")]
        public decimal Purchqty { get; set; }
        [Column("PURCHMARKUP", TypeName = "decimal(18,2)")]
        public decimal Purchmarkup { get; set; }
        [Column("INVENTRECEIVEDNOW", TypeName = "decimal(18,2)")]
        public decimal Inventreceivednow { get; set; }
        [Column("MULTILNDISC", TypeName = "decimal(18,2)")]
        public decimal Multilndisc { get; set; }
        [Column("MULTILNPERCENT", TypeName = "decimal(18,2)")]
        public decimal Multilnpercent { get; set; }
        [Column("PURCHASETYPE")]
        public int Purchasetype { get; set; }
        [Column("COVREF")]
        public int Covref { get; set; }
        [Column("REMAININVENTPHYSICAL", TypeName = "decimal(18,2)")]
        public decimal Remaininventphysical { get; set; }
        [Column("TAXITEMGROUP")]
        public string Taxitemgroup { get; set; } = null!;
        [Column("TRANSACTIONCODE")]
        public string Transactioncode { get; set; } = null!;
        [Column("SHIPPINGDATECONFIRMED")]
        public DateTime Shippingdateconfirmed { get; set; }
        [Column("TAXAUTOGENERATED")]
        public int Taxautogenerated { get; set; }
        [Column("UNDERDELIVERYPCT", TypeName = "decimal(18,2)")]
        public decimal Underdeliverypct { get; set; }
        [Column("OVERDELIVERYPCT", TypeName = "decimal(18,2)")]
        public decimal Overdeliverypct { get; set; }
        [Column("BARCODE")]
        public string Barcode { get; set; } = null!;
        [Column("BARCODETYPE")]
        public string Barcodetype { get; set; } = null!;
        [Column("INVENTREFID")]
        public string Inventrefid { get; set; } = null!;
        [Column("INVENTREFTRANSID")]
        public string Inventreftransid { get; set; } = null!;
        [Column("ITEMREFTYPE")]
        public int Itemreftype { get; set; }
        [Column("PROJTRANSID")]
        public string Projtransid { get; set; } = null!;
        [Column("BLOCKED")]
        public int Blocked { get; set; }
        [Column("COMPLETE")]
        public int Complete { get; set; }
        [Column("REQPLANIDSCHED")]
        public string Reqplanidsched { get; set; } = null!;
        [Column("REQPOID")]
        public string Reqpoid { get; set; } = null!;
        [Column("ITEMBOMID")]
        public string Itembomid { get; set; } = null!;
        [Column("LINEHEADER")]
        public string Lineheader { get; set; } = null!;
        [Column("SCRAP")]
        public int Scrap { get; set; }
        [Column("RETURNACTIONID")]
        public string Returnactionid { get; set; } = null!;
        [Column("PROJCATEGORYID")]
        public string Projcategoryid { get; set; } = null!;
        [Column("PROJID")]
        public string Projid { get; set; } = null!;
        [Column("INVENTDIMID")]
        public string Inventdimid { get; set; } = null!;
        [Column("TRANSPORT")]
        public string Transport { get; set; } = null!;
        [Column("STATPROCID")]
        public string Statprocid { get; set; } = null!;
        [Column("PORT")]
        public string Port { get; set; } = null!;
        [Column("ASSETID")]
        public string Assetid { get; set; } = null!;
        [Column("ASSETTRANSTYPEPURCH")]
        public int Assettranstypepurch { get; set; }
        [Column("ASSETBOOKID")]
        public string Assetbookid { get; set; } = null!;
        [Column("PROJLINEPROPERTYID")]
        public string Projlinepropertyid { get; set; } = null!;
        [Column("PROJTAXITEMGROUPID")]
        public string Projtaxitemgroupid { get; set; } = null!;
        [Column("PROJTAXGROUPID")]
        public string Projtaxgroupid { get; set; } = null!;
        [Column("PROJSALESPRICE", TypeName = "decimal(18,2)")]
        public decimal Projsalesprice { get; set; }
        [Column("PROJSALESCURRENCYID")]
        public string Projsalescurrencyid { get; set; } = null!;
        [Column("PROJSALESUNITID")]
        public string Projsalesunitid { get; set; } = null!;
        [Column("DELIVERYADDRESS")]
        public string Deliveryaddress { get; set; } = null!;
        [Column("DELIVERYNAME")]
        public string Deliveryname { get; set; } = null!;
        [Column("DELIVERYSTREET")]
        public string Deliverystreet { get; set; } = null!;
        [Column("DELIVERYZIPCODE")]
        public string Deliveryzipcode { get; set; } = null!;
        [Column("DELIVERYCITY")]
        public string Deliverycity { get; set; } = null!;
        [Column("DELIVERYCOUNTY")]
        public string Deliverycounty { get; set; } = null!;
        [Column("DELIVERYSTATE")]
        public string Deliverystate { get; set; } = null!;
        [Column("DELIVERYCOUNTRYREGIONID")]
        public string Deliverycountryregionid { get; set; } = null!;
        [Column("DELIVERYTYPE")]
        public int Deliverytype { get; set; }
        [Column("CUSTOMERREF")]
        public string Customerref { get; set; } = null!;
        [Column("CUSTPURCHASEORDERFORMNUM")]
        public string Custpurchaseorderformnum { get; set; } = null!;
        [Column("BLANKETREFTRANSID")]
        public string Blanketreftransid { get; set; } = null!;
        [Column("STATTRIANGULARDEAL")]
        public int Stattriangulardeal { get; set; }
        [Column("REMAININVENTFINANCIAL", TypeName = "decimal(18,2)")]
        public decimal Remaininventfinancial { get; set; }
        [Column("PURCHREQLINEREFID")]
        public Guid Purchreqlinerefid { get; set; }
        [Column("ACTIVITYNUMBER")]
        public string Activitynumber { get; set; } = null!;
        [Column("RETURNSTATUS")]
        public int Returnstatus { get; set; }
        [Column("RETURNDISPOSITIONCODEID")]
        public string Returndispositioncodeid { get; set; } = null!;
        [Column("CREATEFIXEDASSET")]
        public int Createfixedasset { get; set; }
        [Column("ASSETGROUP")]
        public string Assetgroup { get; set; } = null!;
        [Column("REQUISITIONER")]
        public string Requisitioner { get; set; } = null!;
        [Column("REQATTENTION")]
        public string Reqattention { get; set; } = null!;
        [Column("PURCHREQID")]
        public string Purchreqid { get; set; } = null!;
        [Column("CREATEDDATETIME")]
        public DateTime Createddatetime { get; set; }
        [Column("DATAAREAID")]
        public string Dataareaid { get; set; } = null!;
        [Column("RECVERSION")]
        public int Recversion { get; set; }
        [Column("RECID")]
        public long Recid { get; set; }
        [Column("COS_MOTIVOREEMPLAZO")]
        public int CosMotivoreemplazo { get; set; }
        [Column("COS_PURCHQTY", TypeName = "decimal(18,2)")]
        public decimal CosPurchqty { get; set; }
        [Column("COS_PURCHPRICE", TypeName = "decimal(18,2)")]
        public decimal CosPurchprice { get; set; }
        [Column("COS_PURCHUNIT")]
        public string CosPurchunit { get; set; } = null!;
        [Column("COS_ITEMID")]
        public string CosItemid { get; set; } = null!;
        [Column("COS_PURCHID")]
        public string CosPurchid { get; set; } = null!;
        [Column("COS_PURCHLINE")]
        public long CosPurchline { get; set; }
        [Column("CE_LINEACANCELADAENIC")]
        public int CeLineacanceladaenic { get; set; }
        [Column("CE_IDFAMILIA")]
        public long CeIdfamilia { get; set; }
        [Column("CE_EXTERNALITEMID")]
        public string CeExternalitemid { get; set; } = null!;
        [Column("CREATEDBY")] 
        public string Createdby { get; set; } = null!;
    }
}
